baseurl = "https://vineethweb.com/"
title = "Vineeth Pothulapati"
theme = "hugo-theme-nix"
languageCode = "en-us"
disqusShortname = "vineeth"

[menu]
  [[menu.header]]
    name = "posts"
    weight = 0
    url = "post"
  [[menu.header]]
    name = "about"
    weight = 1
    url = "about"
  [[menu.header]]
    name = "talks"
    weight = 2
    url = "talks"
  [[menu.header]]
    name = "readings"
    weight = 3
    url = "readings"  
  [[menu.header]]
    name = "projects"
    weight = 3
    url = "projects"

[params]
  GithubID = "VineethReddy02"
  TwitterID = "vineeetth"
  LinkedInID = "vineeth-pothulapati"
  Name = "Vineeth Pothulapati"
  HeaderUsername = "vineeth"
  HeaderHostname = "Timescale"
  Email = "vineethpothulapati@outlook.com"
  ProfilePicture = "/dp.jpeg"
  Favicon = "/dp.jpeg"

